services:
  - type: web
    name: uself-alpha
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: uself-alpha-db
          property: connectionString
      - key: APP_ENV
        value: production

databases:
  - name: uself-alpha-db
    plan: free
    region: frankfurt
    postgresMajorVersion: "18"
